[package]
name = "idis"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
uuid = "1.13.1"
half = { version = "2.4.1", features = ["serde"] }
chrono = { version = "0.4.39", features = ["serde"] }
serde_json = "1.0.138"
tokio = { version = "1.28.0", features = ["full"] }
libc = "0.2"
vec-plus = "0.1.0"